version: "3.1"

services:
  app:
    container_name: next-skeleton
    image: next-skeleton
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - API_URL="${API_URL}"
    ports:
      - 3000:3000
      - 49153:49153
    volumes:
      - .:/app
